name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install raylib
      run: sudo apt-get update && sudo apt-get install -y libraylib-dev
    - name: make
      run: make
    - name: Test Complete
      run: echo "Test Complete!"
